# COB environment values
replicaCount: 3

image:
  repository: transaction-demo
  tag: cob
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: transaction-demo-cob.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: transaction-demo-cob-tls
      hosts:
        - transaction-demo-cob.example.com

resources:
  limits:
    cpu: 3000m
    memory: 6Gi
  requests:
    cpu: 1500m
    memory: 3Gi

env:
  JAVA_OPTS: "-Xms3g -Xmx3g -XX:+UseG1GC -Xlog:gc*:/tmp/gc-cob.log:time,uptime,level,tags -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof"
  SPRING_PROFILES_ACTIVE: "cob"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 55
  targetMemoryUtilizationPercentage: 55

nodeSelector: {}

tolerations: []

affinity: {}

# COB specific configurations
config:
  logging:
    level: INFO
  cache:
    ttl: 600
  debug:
    enabled: false 