# Default values for transaction-demo
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of replicas (will be overridden by environment-specific values)
replicaCount: 1

# Image configuration
image:
  repository: transaction-demo
  tag: latest
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []

# Name overrides
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: transaction-demo.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource limits and requests (will be overridden by environment-specific values)
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

# Environment variables (will be overridden by environment-specific values)
env:
  SPRING_PROFILES_ACTIVE: "local"
  JAVA_OPTS: "-Xms512m -Xmx512m -XX:+UseG1GC -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError"

# Health check probes
livenessProbe:
  httpGet:
    path: /api/v1/transactions/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /api/v1/transactions/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

# Autoscaling configuration (will be overridden by environment-specific values)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity rules
affinity: {}

# Application configuration (will be overridden by environment-specific values)
config:
  logging:
    level: INFO
  cache:
    ttl: 300
  debug:
    enabled: false 