# Local development environment values
replicaCount: 1

image:
  repository: transaction-demo
  tag: local
  pullPolicy: Never

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: transaction-demo-local.local
  tls: []
  tlsSecret: ""

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

env:
  JAVA_OPTS: "-Xms256m -Xmx256m -XX:+UseG1GC -Xlog:gc*:/tmp/gc-local.log:time,uptime,level,tags -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heapdump.hprof"
  SPRING_PROFILES_ACTIVE: "local"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Local specific configurations
config:
  logging:
    level: DEBUG
  cache:
    ttl: 30
  debug:
    enabled: true 