apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transaction-demo.fullname" . }}
  labels:
    app: {{ include "transaction-demo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "transaction-demo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "transaction-demo.name" . }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "transaction-demo.fullname" . }}
      {{- end }}
      containers:
        - name: {{ include "transaction-demo.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.env.JAVA_OPTS | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }} 